# Generated by Django 4.0.3 on 2022-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='blog.ipaddress', verbose_name='بازدید ها'),
        ),
    ]
