# Generated by Django 4.0.3 on 2022-03-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_article_hits_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
            ],
            options={
                'verbose_name': 'ذخیره مقاله',
                'verbose_name_plural': 'مقاله های ذخیره شده',
            },
        ),
    ]
