# Generated by Django 4.0.3 on 2022-03-22 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_savearticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savearticle',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='savearticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله'),
        ),
    ]
