# Generated by Django 4.0.3 on 2022-07-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_user_savearticle_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='defaultpics/catdefault.jpg', upload_to='categories'),
        ),
    ]
